### ISSUE TITLE
image.dart conflict

### ISSUE THREAD

**Issue by rupamking1** [justacid/blurhash-dart#14]
A value of type 'Image (where Image is defined in C:\Users\Rupam\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\image-3.0.2\lib\src\image.dart)' can't be returned from the function 'CacheBlur' because it has a return type of 'Image (where Image is defined in H:\Framework\FlutterStable\flutter\packages\flutter\lib\src\widgets\image.dart)'.dart(return_of_invalid_type)
image.dart(51, 7): Image is defined in C:\Users\Rupam\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\image-3.0.2\lib\src\image.dart
image.dart(301, 7): Image is defined in H:\Framework\FlutterStable\flutter\packages\flutter\lib\src\widgets\image.dart

**Comment by justacid** [comment]
Seems like you are getting conflicting identifiers because you are trying to use two different image types from two different libraries (package `image` and flutter image). You need to specify a library prefix to resolve this conflict. See https://dart.dev/guides/language/language-tour#using-libraries.
