### ISSUE TITLE
Performance for encoding on mobile client

### ISSUE THREAD

**Issue by aytunch** [justacid/blurhash-dart#4]
I was thinking of encoding the image which I am about to upload to Firestore and upload the BlurHash string along with the image. Do you think this strategy is bad considering I am going to do it in mobile client? I am in a fact distributing the load to clients. Also uploading an image does not happen too often. Furthermore, I can create the BlurHash from a downsized version of the image to increase performance. What do you think?

**Comment by justacid** [comment]
It might be a fine strategy when using Firestore - if you go this route I'd encourage you to downsize the image significantly, since encoding a full-size image is rather slow and you get no additional benefit from that. In fact, I believe that is the strategy used on https://blurha.sh/ (but I have not actually checked the source).
