### ISSUE TITLE
Speed of encoding

### ISSUE THREAD

**Issue by shinyford** [justacid/blurhash-dart#7]
Hi! Can I ask what sort of time you'd expect an image to be encoded to blurhash in? Do you resize your images before encoding, and if so to what size? 

I'm trying to find the best balance for near-instantaneous performance (from a UX perspective) but I'm wondering if that's a vain hope. All implementations (server side too) seem pretty slow... but maybe I'm doing something wrong.

**Comment by justacid** [comment]
Hi! Encoding isn't particularly fast on full-size images as you noticed. Unfortunately, I haven't had much opportunity to test the speed of the dart encoder (we are using a go implementation server side), but it should be roughly similar to the decoder. The good news is you should be able to resize the image significantly before encoding - you will lose detail I guess, but that's the whole point anyway. Honestly, your best bet is probably just trying it out with different sizes.

**Comment by shinyford** [comment]
Thanks for the reply. Currently resizing to a 20x20 square, which seems to perform reasonable (c. 250ms). Getting similar performance from a server-side Elixir implementation now too, FWIW.

**Comment by gargakshit** [comment]
Hey @shinyford 
Did you use an isolate to compute the blurhash, as I am also computing one for a 20x20 image, and 250ms might hang the UI thread 🤔 
Regards

**Comment by mitesh77** [comment]
can you add "encodeBlurHash" function as async so we don't face performance issues and user bad experience.

**Comment by gargakshit** [comment]
Tbh, isolates work well. I use it to both resize the image and produce a blurhash, with no lag or jankyness

**Comment by justacid** [comment]
Marking `encodeBlurHash` async would **not** help, since Dart and Flutter (which I guess this is mostly about) are inherently single-threaded. Hence, naively marking it async would still block the UI thread. As @gargakshit suggested _isolates_ are the way to go and flutter even has a helper function which makes their usage fairly trivial. One could, for example, write a simple wrapper, doing something like this (untested):

```dart
import 'package:blurhash_dart/blurhash_dart.dart';
import 'package:flutter/foundation.dart';

class BlurHashParams {
  const BlurHashParams(
    this.data, 
    this.width,
    this.height, {
    this.numCompX = 4, 
    this.numCompY = 3,
  });

  final Uint8List data;
  final int width;
  final int height; 
  final int numCompX;
  final int numCompY;
}

String _encodeHashWithParams(BlurHashParams params) {
  return encodeBlurHash(
    params.data, 
    params.width,
    params.height, 
    numCompX: params.numCompX, 
    numCompY: params.numCompY,
  );
}

Future<String> encodeBlurHashAsync(BlurHashParams params) async {
  return compute(_encodeHashWithParams, params);
}
```
The compute function is from the [Flutter foundation](https://api.flutter.dev/flutter/foundation/compute.html) library. Note that `_encodeHashWithParams` is a top-level function, which is a requirement imposed by Dart; from the documentation: _"The callback argument must be a top-level function, not a closure or an instance or static method of a class."_
Together with resizing the image beforehand, this should alleviate any performance problems (and not block the UI thread under any circumstances).

I'd like to keep this package focused on the core algorithm itself, but if there is demand I might incorporate this in the library itself. I'll close the issue, but feel free to comment, if there are any questions.

**Comment by metehanpinarli** [comment]
How can we resize the image to speed up the time. I take the image from the user's phone and send it to the server

**Comment by justacid** [comment]
You can use the `copyResize` function from the [image](https://pub.dev/documentation/image/latest/image/copyResize.html) package.
